cockroach:
  host: localhost
  name: us_metadata
  port: 26257
  user: root
mongo:
  dbName: eseventstore
  url: mongodb://localhost:27017
pulsar:
  url: pulsar://localhost:6650
  topic: events
secret: secret

