cockroach:
  host: localhost
  name: us_metadata
  port: 26257
  user: root
mongo:
  dbName: urlShortener
  uri: mongodb://localhost:27017
redis:
  address: localhost
  addressPort: 6379
pulsar:
  url: pulsar://localhost:6650
  topic: events
secret: secret

