cockroach:
  host: cockroachdb
  name: us_metadata
  port: 26257
  user: root
mongo:
  dbName: urlShortener
  uri: mongodb://root:password@mongo:27012
redis:
  address: redis
  addressPort: 6379
pulsar:
  url: pulsar://pulsar:6650
  topic: events
secret: secret

